---
site_name: "NFDI4Chem_MIChI"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://NFDI4Chem.github.io/NFDI4Chem_MIChI
repo_url: https://github.com/NFDI4Chem/NFDI4Chem_MIChI

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
